export const INFO_FETCH_USER_REQUEST = 'INFO_FETCH_USER_REQUEST'
export const INFO_FETCH_USER_SUCCESS = 'INFO_FETCH_USER_SUCCESS'
export const INFO_FETCH_USER_FAIL = 'INFO_FETCH_USER_FAIL'

export const INFO_UPLOAD_REQUEST = 'INFO_UPLOAD_REQUEST'
export const INFO_UPLOAD_SUCCESS = 'INFO_UPLOAD_SUCCESS'
export const INFO_UPLOAD_FAIL = 'INFO_UPLOAD_FAIL'

export const LOGIN_REGIST_REQUEST = 'LOGIN_REGIST_REQUEST'
export const LOGIN_REGIST_SUCCESS = 'LOGIN_REGIST_SUCCESS'
export const LOGIN_REGIST_FAIL = 'LOGIN_REGIST_FAIL'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
